"""empty message

Revision ID: 496375203757
Revises: 
Create Date: 2018-06-14 00:57:11.761946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496375203757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.Text(), nullable=True),
    sa.Column('second', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Theater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('am_auditorium', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Auditorium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('id_theater', sa.Integer(), nullable=True),
    sa.Column('am_seats', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_theater'], ['Theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Spectacle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('id_theater', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_theater'], ['Theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Screening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_auditorium', sa.Integer(), nullable=True),
    sa.Column('id_spectacle', sa.Integer(), nullable=True),
    sa.Column('id_theater', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_auditorium'], ['Auditorium.id'], ),
    sa.ForeignKeyConstraint(['id_spectacle'], ['Spectacle.id'], ),
    sa.ForeignKeyConstraint(['id_theater'], ['Theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('id_auditorium', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_auditorium'], ['Auditorium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_theater', sa.Integer(), nullable=True),
    sa.Column('id_screening', sa.Integer(), nullable=True),
    sa.Column('reservation_name', sa.Text(), nullable=True),
    sa.Column('reservation_number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_screening'], ['Screening.id'], ),
    sa.ForeignKeyConstraint(['id_theater'], ['Theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SeatReserved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_screening', sa.Integer(), nullable=True),
    sa.Column('id_reservation', sa.Integer(), nullable=True),
    sa.Column('id_seat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_reservation'], ['Reservation.id'], ),
    sa.ForeignKeyConstraint(['id_screening'], ['Screening.id'], ),
    sa.ForeignKeyConstraint(['id_seat'], ['Seat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SeatReserved')
    op.drop_table('Reservation')
    op.drop_table('Seat')
    op.drop_table('Screening')
    op.drop_table('Spectacle')
    op.drop_table('Auditorium')
    op.drop_table('Theater')
    op.drop_table('Administrators')
    # ### end Alembic commands ###
