"""empty message

Revision ID: e2b0b8b707c7
Revises: 496375203757
Create Date: 2018-06-25 22:33:51.162355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b0b8b707c7'
down_revision = '496375203757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SeatReserved', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('SeatReserved', sa.Column('row', sa.Integer(), nullable=True))
    op.drop_column('SeatReserved', 'id_seat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SeatReserved', sa.Column('id_seat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('SeatReserved', 'row')
    op.drop_column('SeatReserved', 'number')
    # ### end Alembic commands ###
